apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ecom-frontend-app
  namespace: argocd

spec:
  project: default
  
  source:
    repoURL: https://github.com/himansusekharsahoo/ecom.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
