apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-frontend-ingress
  labels:
    app.kubernetes.io/name: ecom-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ecom.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ecom-frontend-service
            port: 
              number: 80
              
